package christmaschessgame;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

public class ABoard extends javax.swing.JFrame {

    private static String PieceSelected;
    public static String Go = "white";
    public static String PieceMoved;
    public static String PieceChosen;
    public static String SelectORMove = "Select";
    public static JButton LastClicked;
    public static String fullDir;
    public static Color LastClickedColor;
    public static boolean MoveSpaceFree;
    public static String ColourMatching;
    public static JButton NewPiece;
    public static JButton NewClicked;

    public ABoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        ButtonE8 = new javax.swing.JButton();
        ButtonG1 = new javax.swing.JButton();
        ButtonH1 = new javax.swing.JButton();
        ButtonF1 = new javax.swing.JButton();
        ButtonE1 = new javax.swing.JButton();
        ButtonC1 = new javax.swing.JButton();
        ButtonD1 = new javax.swing.JButton();
        ButtonB1 = new javax.swing.JButton();
        ButtonA1 = new javax.swing.JButton();
        ButtonH7 = new javax.swing.JButton();
        ButtonG7 = new javax.swing.JButton();
        ButtonF7 = new javax.swing.JButton();
        ButtonE7 = new javax.swing.JButton();
        ButtonD7 = new javax.swing.JButton();
        ButtonC7 = new javax.swing.JButton();
        ButtonB7 = new javax.swing.JButton();
        ButtonA7 = new javax.swing.JButton();
        ButtonH5 = new javax.swing.JButton();
        ButtonA6 = new javax.swing.JButton();
        ButtonB6 = new javax.swing.JButton();
        ButtonC6 = new javax.swing.JButton();
        ButtonD6 = new javax.swing.JButton();
        ButtonE6 = new javax.swing.JButton();
        ButtonF6 = new javax.swing.JButton();
        ButtonH6 = new javax.swing.JButton();
        ButtonG6 = new javax.swing.JButton();
        ButtonG5 = new javax.swing.JButton();
        ButtonF5 = new javax.swing.JButton();
        ButtonE5 = new javax.swing.JButton();
        ButtonD5 = new javax.swing.JButton();
        ButtonC5 = new javax.swing.JButton();
        ButtonB5 = new javax.swing.JButton();
        ButtonA5 = new javax.swing.JButton();
        ButtonE3 = new javax.swing.JButton();
        ButtonB4 = new javax.swing.JButton();
        ButtonD3 = new javax.swing.JButton();
        ButtonD4 = new javax.swing.JButton();
        ButtonG3 = new javax.swing.JButton();
        ButtonB3 = new javax.swing.JButton();
        ButtonA4 = new javax.swing.JButton();
        ButtonH4 = new javax.swing.JButton();
        ButtonC3 = new javax.swing.JButton();
        ButtonA3 = new javax.swing.JButton();
        ButtonE4 = new javax.swing.JButton();
        ButtonF4 = new javax.swing.JButton();
        ButtonF3 = new javax.swing.JButton();
        ButtonC4 = new javax.swing.JButton();
        ButtonG4 = new javax.swing.JButton();
        ButtonH3 = new javax.swing.JButton();
        ButtonB2 = new javax.swing.JButton();
        ButtonA8 = new javax.swing.JButton();
        ButtonH8 = new javax.swing.JButton();
        ButtonF2 = new javax.swing.JButton();
        ButtonG8 = new javax.swing.JButton();
        ButtonA2 = new javax.swing.JButton();
        ButtonC2 = new javax.swing.JButton();
        ButtonF8 = new javax.swing.JButton();
        ButtonG2 = new javax.swing.JButton();
        ButtonE2 = new javax.swing.JButton();
        ButtonD8 = new javax.swing.JButton();
        ButtonD2 = new javax.swing.JButton();
        ButtonH2 = new javax.swing.JButton();
        ButtonB8 = new javax.swing.JButton();
        ButtonC8 = new javax.swing.JButton();
        NewBlack_Bishop = new javax.swing.JButton();
        NewBlack_Knight = new javax.swing.JButton();
        NewBlack_Rook = new javax.swing.JButton();
        NewBlack_Queen = new javax.swing.JButton();
        NewWhite_Rook = new javax.swing.JButton();
        NewWhite_Bishop = new javax.swing.JButton();
        NewWhite_Knight = new javax.swing.JButton();
        NewWhite_Queen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        WhoGO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Warning = new javax.swing.JLabel();
        Warning1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ButtonE8.setBackground(new java.awt.Color(255, 255, 255));
        ButtonE8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Black_king.png"))); // NOI18N
        ButtonE8.setText("Black_king");
        ButtonE8.setToolTipText("");
        ButtonE8.setActionCommand("jToggleButtonE8");
        ButtonE8.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonE8.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonE8.setName("ButtonE8"); // NOI18N
        ButtonE8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonE8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE8);
        ButtonE8.setBounds(240, 0, 60, 60);

        ButtonG1.setBackground(new java.awt.Color(161, 80, 5));
        ButtonG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_White.png"))); // NOI18N
        ButtonG1.setText("Knight_White");
        ButtonG1.setToolTipText("");
        ButtonG1.setActionCommand("jToggleButtonG1");
        ButtonG1.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonG1.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonG1.setName("ButtonG1"); // NOI18N
        ButtonG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonG1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonG1);
        ButtonG1.setBounds(360, 420, 60, 60);

        ButtonH1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_White.png"))); // NOI18N
        ButtonH1.setText("Rook_White");
        ButtonH1.setToolTipText("");
        ButtonH1.setActionCommand("jToggleButtonH1");
        ButtonH1.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonH1.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonH1.setName("ButtonH1"); // NOI18N
        ButtonH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonH1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonH1);
        ButtonH1.setBounds(420, 420, 60, 60);

        ButtonF1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Bishop_White.png"))); // NOI18N
        ButtonF1.setText("Bishop_White");
        ButtonF1.setToolTipText("");
        ButtonF1.setActionCommand("jToggleButtonF1");
        ButtonF1.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonF1.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonF1.setName("ButtonF1"); // NOI18N
        ButtonF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonF1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF1);
        ButtonF1.setBounds(300, 420, 60, 60);

        ButtonE1.setBackground(new java.awt.Color(161, 80, 5));
        ButtonE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/King_White.png"))); // NOI18N
        ButtonE1.setText("King_White");
        ButtonE1.setToolTipText("");
        ButtonE1.setActionCommand("jToggleButtonE1");
        ButtonE1.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonE1.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonE1.setName("ButtonE1"); // NOI18N
        ButtonE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonE1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE1);
        ButtonE1.setBounds(240, 420, 60, 60);

        ButtonC1.setBackground(new java.awt.Color(161, 80, 5));
        ButtonC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Bishop_White.png"))); // NOI18N
        ButtonC1.setText("Bishop_White");
        ButtonC1.setToolTipText("");
        ButtonC1.setActionCommand("jToggleButtonC1");
        ButtonC1.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonC1.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonC1.setName("ButtonC1"); // NOI18N
        ButtonC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonC1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC1);
        ButtonC1.setBounds(120, 420, 60, 60);

        ButtonD1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Queen_white.png"))); // NOI18N
        ButtonD1.setText("Queen_white");
        ButtonD1.setToolTipText("");
        ButtonD1.setActionCommand("jToggleButtonD1");
        ButtonD1.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonD1.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonD1.setName("ButtonD1"); // NOI18N
        ButtonD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonD1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD1);
        ButtonD1.setBounds(180, 420, 60, 60);

        ButtonB1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_White.png"))); // NOI18N
        ButtonB1.setText("Knight_White");
        ButtonB1.setToolTipText("");
        ButtonB1.setActionCommand("jToggleButtonB1");
        ButtonB1.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonB1.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonB1.setName("ButtonB1"); // NOI18N
        ButtonB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonB1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB1);
        ButtonB1.setBounds(60, 420, 60, 60);

        ButtonA1.setBackground(new java.awt.Color(161, 80, 5));
        ButtonA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_White.png"))); // NOI18N
        ButtonA1.setText("Rook_White");
        ButtonA1.setToolTipText("");
        ButtonA1.setActionCommand("jToggleButtonA1");
        ButtonA1.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonA1.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonA1.setName("ButtonA1"); // NOI18N
        ButtonA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonA1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA1);
        ButtonA1.setBounds(0, 420, 60, 60);

        ButtonH7.setBackground(new java.awt.Color(255, 255, 255));
        ButtonH7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png"))); // NOI18N
        ButtonH7.setText("Pawn_Black");
        ButtonH7.setToolTipText("");
        ButtonH7.setActionCommand("jToggleButtonH7");
        ButtonH7.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonH7.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonH7.setName("ButtonH7"); // NOI18N
        ButtonH7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonH7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonH7);
        ButtonH7.setBounds(420, 60, 60, 60);

        ButtonG7.setBackground(new java.awt.Color(161, 80, 5));
        ButtonG7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png"))); // NOI18N
        ButtonG7.setText("Pawn_Black");
        ButtonG7.setToolTipText("");
        ButtonG7.setActionCommand("jToggleButtonG7");
        ButtonG7.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonG7.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonG7.setName("ButtonG7"); // NOI18N
        ButtonG7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonG7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonG7);
        ButtonG7.setBounds(360, 60, 60, 60);

        ButtonF7.setBackground(new java.awt.Color(255, 255, 255));
        ButtonF7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png"))); // NOI18N
        ButtonF7.setText("Pawn_Black");
        ButtonF7.setToolTipText("");
        ButtonF7.setActionCommand("jToggleButtonF7");
        ButtonF7.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonF7.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonF7.setName("ButtonF7"); // NOI18N
        ButtonF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonF7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF7);
        ButtonF7.setBounds(300, 60, 60, 60);

        ButtonE7.setBackground(new java.awt.Color(161, 80, 5));
        ButtonE7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png"))); // NOI18N
        ButtonE7.setText("Pawn_Black");
        ButtonE7.setToolTipText("");
        ButtonE7.setActionCommand("jToggleButtonE7");
        ButtonE7.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonE7.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonE7.setName("ButtonE7"); // NOI18N
        ButtonE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonE7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE7);
        ButtonE7.setBounds(240, 60, 60, 60);

        ButtonD7.setBackground(new java.awt.Color(255, 255, 255));
        ButtonD7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png"))); // NOI18N
        ButtonD7.setText("Pawn_Black");
        ButtonD7.setToolTipText("");
        ButtonD7.setActionCommand("jToggleButtonD7");
        ButtonD7.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonD7.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonD7.setName("ButtonD7"); // NOI18N
        ButtonD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonD7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD7);
        ButtonD7.setBounds(180, 60, 60, 60);

        ButtonC7.setBackground(new java.awt.Color(161, 80, 5));
        ButtonC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png"))); // NOI18N
        ButtonC7.setText("Pawn_Black");
        ButtonC7.setToolTipText("");
        ButtonC7.setActionCommand("jToggleButtonC7");
        ButtonC7.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonC7.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonC7.setName("ButtonC7"); // NOI18N
        ButtonC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonC7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC7);
        ButtonC7.setBounds(120, 60, 60, 60);

        ButtonB7.setBackground(new java.awt.Color(255, 255, 255));
        ButtonB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png"))); // NOI18N
        ButtonB7.setText("Pawn_Black");
        ButtonB7.setToolTipText("");
        ButtonB7.setActionCommand("jToggleButtonB7");
        ButtonB7.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonB7.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonB7.setName("ButtonB7"); // NOI18N
        ButtonB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonB7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB7);
        ButtonB7.setBounds(60, 60, 60, 60);

        ButtonA7.setBackground(new java.awt.Color(161, 80, 5));
        ButtonA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png"))); // NOI18N
        ButtonA7.setText("Pawn_Black");
        ButtonA7.setToolTipText("");
        ButtonA7.setActionCommand("jToggleButtonA7");
        ButtonA7.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonA7.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonA7.setName("ButtonA7"); // NOI18N
        ButtonA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonA7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA7);
        ButtonA7.setBounds(0, 60, 60, 60);

        ButtonH5.setBackground(new java.awt.Color(255, 255, 255));
        ButtonH5.setToolTipText("");
        ButtonH5.setActionCommand("jToggleButtonH5");
        ButtonH5.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonH5.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonH5.setName("ButtonH5"); // NOI18N
        ButtonH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonH5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonH5);
        ButtonH5.setBounds(420, 180, 60, 60);

        ButtonA6.setBackground(new java.awt.Color(255, 255, 255));
        ButtonA6.setToolTipText("");
        ButtonA6.setActionCommand("jToggleButtonA6");
        ButtonA6.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonA6.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonA6.setName("ButtonA6"); // NOI18N
        ButtonA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonA6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA6);
        ButtonA6.setBounds(0, 120, 60, 60);

        ButtonB6.setBackground(new java.awt.Color(161, 80, 5));
        ButtonB6.setToolTipText("");
        ButtonB6.setActionCommand("jToggleButtonB6");
        ButtonB6.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonB6.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonB6.setName("ButtonB6"); // NOI18N
        ButtonB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonB6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB6);
        ButtonB6.setBounds(60, 120, 60, 60);

        ButtonC6.setBackground(new java.awt.Color(255, 255, 255));
        ButtonC6.setToolTipText("");
        ButtonC6.setActionCommand("jToggleButtonC6");
        ButtonC6.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonC6.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonC6.setName("ButtonC6"); // NOI18N
        ButtonC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonC6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC6);
        ButtonC6.setBounds(120, 120, 60, 60);

        ButtonD6.setBackground(new java.awt.Color(161, 80, 5));
        ButtonD6.setToolTipText("");
        ButtonD6.setActionCommand("jToggleButtonD6");
        ButtonD6.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonD6.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonD6.setName("ButtonD6"); // NOI18N
        ButtonD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonD6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD6);
        ButtonD6.setBounds(180, 120, 60, 60);

        ButtonE6.setBackground(new java.awt.Color(255, 255, 255));
        ButtonE6.setToolTipText("");
        ButtonE6.setActionCommand("jToggleButtonE6");
        ButtonE6.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonE6.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonE6.setName("ButtonE6"); // NOI18N
        ButtonE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonE6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE6);
        ButtonE6.setBounds(240, 120, 60, 60);

        ButtonF6.setBackground(new java.awt.Color(161, 80, 5));
        ButtonF6.setToolTipText("");
        ButtonF6.setActionCommand("jToggleButtonF6");
        ButtonF6.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonF6.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonF6.setName("ButtonF6"); // NOI18N
        ButtonF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonF6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF6);
        ButtonF6.setBounds(300, 120, 60, 60);

        ButtonH6.setBackground(new java.awt.Color(161, 80, 5));
        ButtonH6.setToolTipText("");
        ButtonH6.setActionCommand("jToggleButtonH6");
        ButtonH6.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonH6.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonH6.setName("ButtonH6"); // NOI18N
        ButtonH6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonH6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonH6);
        ButtonH6.setBounds(420, 120, 60, 60);

        ButtonG6.setBackground(new java.awt.Color(255, 255, 255));
        ButtonG6.setToolTipText("");
        ButtonG6.setActionCommand("jToggleButtonG6");
        ButtonG6.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonG6.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonG6.setName("ButtonG6"); // NOI18N
        ButtonG6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonG6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonG6);
        ButtonG6.setBounds(360, 120, 60, 60);

        ButtonG5.setBackground(new java.awt.Color(161, 80, 5));
        ButtonG5.setToolTipText("");
        ButtonG5.setActionCommand("jToggleButtonG5");
        ButtonG5.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonG5.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonG5.setName("ButtonG5"); // NOI18N
        ButtonG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonG5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonG5);
        ButtonG5.setBounds(360, 180, 60, 60);

        ButtonF5.setBackground(new java.awt.Color(255, 255, 255));
        ButtonF5.setToolTipText("");
        ButtonF5.setActionCommand("jToggleButtonF5");
        ButtonF5.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonF5.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonF5.setName("ButtonF5"); // NOI18N
        ButtonF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonF5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF5);
        ButtonF5.setBounds(300, 180, 60, 60);

        ButtonE5.setBackground(new java.awt.Color(161, 80, 5));
        ButtonE5.setToolTipText("");
        ButtonE5.setActionCommand("jToggleButtonE5");
        ButtonE5.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonE5.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonE5.setName("ButtonE5"); // NOI18N
        ButtonE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonE5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE5);
        ButtonE5.setBounds(240, 180, 60, 60);

        ButtonD5.setBackground(new java.awt.Color(255, 255, 255));
        ButtonD5.setToolTipText("");
        ButtonD5.setActionCommand("jToggleButtonD5");
        ButtonD5.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonD5.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonD5.setName("ButtonD5"); // NOI18N
        ButtonD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonD5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD5);
        ButtonD5.setBounds(180, 180, 60, 60);

        ButtonC5.setBackground(new java.awt.Color(161, 80, 5));
        ButtonC5.setToolTipText("");
        ButtonC5.setActionCommand("jToggleButtonC5");
        ButtonC5.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonC5.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonC5.setName("ButtonC5"); // NOI18N
        ButtonC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonC5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC5);
        ButtonC5.setBounds(120, 180, 60, 60);

        ButtonB5.setBackground(new java.awt.Color(255, 255, 255));
        ButtonB5.setToolTipText("");
        ButtonB5.setActionCommand("jToggleButtonB5");
        ButtonB5.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonB5.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonB5.setName("ButtonB5"); // NOI18N
        ButtonB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonB5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB5);
        ButtonB5.setBounds(60, 180, 60, 60);

        ButtonA5.setBackground(new java.awt.Color(161, 80, 5));
        ButtonA5.setToolTipText("");
        ButtonA5.setActionCommand("jToggleButtonA5");
        ButtonA5.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonA5.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonA5.setName("ButtonA5"); // NOI18N
        ButtonA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonA5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA5);
        ButtonA5.setBounds(0, 180, 60, 60);

        ButtonE3.setBackground(new java.awt.Color(161, 80, 5));
        ButtonE3.setToolTipText("");
        ButtonE3.setActionCommand("jToggleButtonE3");
        ButtonE3.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonE3.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonE3.setName("ButtonE3"); // NOI18N
        ButtonE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonE3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE3);
        ButtonE3.setBounds(240, 300, 60, 60);

        ButtonB4.setBackground(new java.awt.Color(161, 80, 5));
        ButtonB4.setToolTipText("");
        ButtonB4.setActionCommand("jToggleButtonB4");
        ButtonB4.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonB4.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonB4.setName("ButtonB4"); // NOI18N
        ButtonB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonB4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB4);
        ButtonB4.setBounds(60, 240, 60, 60);

        ButtonD3.setBackground(new java.awt.Color(255, 255, 255));
        ButtonD3.setToolTipText("");
        ButtonD3.setActionCommand("jToggleButtonD3");
        ButtonD3.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonD3.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonD3.setName("ButtonD3"); // NOI18N
        ButtonD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonD3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD3);
        ButtonD3.setBounds(180, 300, 60, 60);

        ButtonD4.setBackground(new java.awt.Color(161, 80, 5));
        ButtonD4.setToolTipText("");
        ButtonD4.setActionCommand("jToggleButtonD4");
        ButtonD4.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonD4.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonD4.setName("ButtonD4"); // NOI18N
        ButtonD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonD4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD4);
        ButtonD4.setBounds(180, 240, 60, 60);

        ButtonG3.setBackground(new java.awt.Color(161, 80, 5));
        ButtonG3.setToolTipText("");
        ButtonG3.setActionCommand("jToggleButtonG3");
        ButtonG3.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonG3.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonG3.setName("ButtonG3"); // NOI18N
        ButtonG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonG3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonG3);
        ButtonG3.setBounds(360, 300, 60, 60);

        ButtonB3.setBackground(new java.awt.Color(255, 255, 255));
        ButtonB3.setToolTipText("");
        ButtonB3.setActionCommand("jToggleButtonB3");
        ButtonB3.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonB3.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonB3.setName("ButtonB3"); // NOI18N
        ButtonB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonB3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB3);
        ButtonB3.setBounds(60, 300, 60, 60);

        ButtonA4.setBackground(new java.awt.Color(255, 255, 255));
        ButtonA4.setToolTipText("");
        ButtonA4.setActionCommand("jToggleButtonA4");
        ButtonA4.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonA4.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonA4.setName("ButtonA4"); // NOI18N
        ButtonA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonA4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA4);
        ButtonA4.setBounds(0, 240, 60, 60);

        ButtonH4.setBackground(new java.awt.Color(161, 80, 5));
        ButtonH4.setToolTipText("");
        ButtonH4.setActionCommand("jToggleButtonH4");
        ButtonH4.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonH4.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonH4.setName("ButtonH4"); // NOI18N
        ButtonH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonH4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonH4);
        ButtonH4.setBounds(420, 240, 60, 60);

        ButtonC3.setBackground(new java.awt.Color(161, 80, 5));
        ButtonC3.setToolTipText("");
        ButtonC3.setActionCommand("jToggleButtonC3");
        ButtonC3.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonC3.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonC3.setName("ButtonC3"); // NOI18N
        ButtonC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonC3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC3);
        ButtonC3.setBounds(120, 300, 60, 60);

        ButtonA3.setBackground(new java.awt.Color(161, 80, 5));
        ButtonA3.setToolTipText("");
        ButtonA3.setActionCommand("jToggleButtonA3");
        ButtonA3.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonA3.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonA3.setName("ButtonA3"); // NOI18N
        ButtonA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonA3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA3);
        ButtonA3.setBounds(0, 300, 60, 60);

        ButtonE4.setBackground(new java.awt.Color(255, 255, 255));
        ButtonE4.setToolTipText("");
        ButtonE4.setActionCommand("jToggleButtonE4");
        ButtonE4.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonE4.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonE4.setName("ButtonE4"); // NOI18N
        ButtonE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonE4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE4);
        ButtonE4.setBounds(240, 240, 60, 60);

        ButtonF4.setBackground(new java.awt.Color(161, 80, 5));
        ButtonF4.setToolTipText("");
        ButtonF4.setActionCommand("jToggleButtonF4");
        ButtonF4.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonF4.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonF4.setName("ButtonF4"); // NOI18N
        ButtonF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonF4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF4);
        ButtonF4.setBounds(300, 240, 60, 60);

        ButtonF3.setBackground(new java.awt.Color(255, 255, 255));
        ButtonF3.setToolTipText("");
        ButtonF3.setActionCommand("jToggleButtonF3");
        ButtonF3.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonF3.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonF3.setName("ButtonF3"); // NOI18N
        ButtonF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonF3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF3);
        ButtonF3.setBounds(300, 300, 60, 60);

        ButtonC4.setBackground(new java.awt.Color(255, 255, 255));
        ButtonC4.setToolTipText("");
        ButtonC4.setActionCommand("jToggleButtonC4");
        ButtonC4.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonC4.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonC4.setName("ButtonC4"); // NOI18N
        ButtonC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonC4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC4);
        ButtonC4.setBounds(120, 240, 60, 60);

        ButtonG4.setBackground(new java.awt.Color(255, 255, 255));
        ButtonG4.setToolTipText("");
        ButtonG4.setActionCommand("jToggleButtonG4");
        ButtonG4.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonG4.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonG4.setName("ButtonG4"); // NOI18N
        ButtonG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonG4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonG4);
        ButtonG4.setBounds(360, 240, 60, 60);

        ButtonH3.setBackground(new java.awt.Color(255, 255, 255));
        ButtonH3.setToolTipText("");
        ButtonH3.setActionCommand("jToggleButtonH3");
        ButtonH3.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonH3.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonH3.setName("ButtonH3"); // NOI18N
        ButtonH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonH3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonH3);
        ButtonH3.setBounds(420, 300, 60, 60);

        ButtonB2.setBackground(new java.awt.Color(161, 80, 5));
        ButtonB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png"))); // NOI18N
        ButtonB2.setText("Pawn_White");
        ButtonB2.setToolTipText("");
        ButtonB2.setActionCommand("jToggleButtonB2");
        ButtonB2.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonB2.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonB2.setName("ButtonB2"); // NOI18N
        ButtonB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonB2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB2);
        ButtonB2.setBounds(60, 360, 60, 60);

        ButtonA8.setBackground(new java.awt.Color(255, 255, 255));
        ButtonA8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_Black.png"))); // NOI18N
        ButtonA8.setText("Rook_Black");
        ButtonA8.setToolTipText("");
        ButtonA8.setActionCommand("jToggleButtonA8");
        ButtonA8.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonA8.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonA8.setName("ButtonA8"); // NOI18N
        ButtonA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonA8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA8);
        ButtonA8.setBounds(0, 0, 60, 60);

        ButtonH8.setBackground(new java.awt.Color(161, 80, 5));
        ButtonH8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_Black.png"))); // NOI18N
        ButtonH8.setText("Rook_Black");
        ButtonH8.setToolTipText("");
        ButtonH8.setActionCommand("jToggleButtonH8");
        ButtonH8.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonH8.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonH8.setName("ButtonH8"); // NOI18N
        ButtonH8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonH8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonH8);
        ButtonH8.setBounds(420, 0, 60, 60);

        ButtonF2.setBackground(new java.awt.Color(161, 80, 5));
        ButtonF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png"))); // NOI18N
        ButtonF2.setText("Pawn_White");
        ButtonF2.setToolTipText("");
        ButtonF2.setActionCommand("jToggleButtonF2");
        ButtonF2.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonF2.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonF2.setName("ButtonF2"); // NOI18N
        ButtonF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonF2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF2);
        ButtonF2.setBounds(300, 360, 60, 60);

        ButtonG8.setBackground(new java.awt.Color(255, 255, 255));
        ButtonG8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_Black.png"))); // NOI18N
        ButtonG8.setText("Knight_Black");
        ButtonG8.setToolTipText("");
        ButtonG8.setActionCommand("jToggleButtonG8");
        ButtonG8.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonG8.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonG8.setName("ButtonG8"); // NOI18N
        ButtonG8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonG8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonG8);
        ButtonG8.setBounds(360, 0, 60, 60);

        ButtonA2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png"))); // NOI18N
        ButtonA2.setText("Pawn_White");
        ButtonA2.setToolTipText("");
        ButtonA2.setActionCommand("jToggleButtonA2");
        ButtonA2.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonA2.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonA2.setName("ButtonA2"); // NOI18N
        ButtonA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonA2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA2);
        ButtonA2.setBounds(0, 360, 60, 60);

        ButtonC2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png"))); // NOI18N
        ButtonC2.setText("Pawn_White");
        ButtonC2.setToolTipText("");
        ButtonC2.setActionCommand("jToggleButtonC2");
        ButtonC2.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonC2.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonC2.setName("ButtonC2"); // NOI18N
        ButtonC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonC2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC2);
        ButtonC2.setBounds(120, 360, 60, 60);

        ButtonF8.setBackground(new java.awt.Color(161, 80, 5));
        ButtonF8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Black_Bishop.png"))); // NOI18N
        ButtonF8.setText("Black_Bishop");
        ButtonF8.setToolTipText("");
        ButtonF8.setActionCommand("jToggleButtonF8");
        ButtonF8.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonF8.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonF8.setName("ButtonF8"); // NOI18N
        ButtonF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonF8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF8);
        ButtonF8.setBounds(300, 0, 60, 60);

        ButtonG2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png"))); // NOI18N
        ButtonG2.setText("Pawn_White");
        ButtonG2.setToolTipText("");
        ButtonG2.setActionCommand("jToggleButtonG2");
        ButtonG2.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonG2.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonG2.setName("ButtonG2"); // NOI18N
        ButtonG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonG2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonG2);
        ButtonG2.setBounds(360, 360, 60, 60);

        ButtonE2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png"))); // NOI18N
        ButtonE2.setText("Pawn_White");
        ButtonE2.setToolTipText("");
        ButtonE2.setActionCommand("jToggleButtonE2");
        ButtonE2.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonE2.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonE2.setName("ButtonE2"); // NOI18N
        ButtonE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonE2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE2);
        ButtonE2.setBounds(240, 360, 60, 60);

        ButtonD8.setBackground(new java.awt.Color(161, 80, 5));
        ButtonD8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Queen_Black.png"))); // NOI18N
        ButtonD8.setText("Queen_Black");
        ButtonD8.setToolTipText("");
        ButtonD8.setActionCommand("jToggleButtonD8");
        ButtonD8.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonD8.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonD8.setName("ButtonD8"); // NOI18N
        ButtonD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonD8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD8);
        ButtonD8.setBounds(180, 0, 60, 60);

        ButtonD2.setBackground(new java.awt.Color(161, 80, 5));
        ButtonD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png"))); // NOI18N
        ButtonD2.setText("Pawn_White");
        ButtonD2.setToolTipText("");
        ButtonD2.setActionCommand("jToggleButtonD2");
        ButtonD2.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonD2.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonD2.setName("ButtonD2"); // NOI18N
        ButtonD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonD2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD2);
        ButtonD2.setBounds(180, 360, 60, 60);

        ButtonH2.setBackground(new java.awt.Color(161, 80, 5));
        ButtonH2.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        ButtonH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png"))); // NOI18N
        ButtonH2.setText("Pawn_White");
        ButtonH2.setToolTipText("");
        ButtonH2.setActionCommand("jToggleButtonH2");
        ButtonH2.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonH2.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonH2.setName("ButtonH2"); // NOI18N
        ButtonH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonH2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonH2);
        ButtonH2.setBounds(420, 360, 60, 60);

        ButtonB8.setBackground(new java.awt.Color(161, 80, 5));
        ButtonB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_Black.png"))); // NOI18N
        ButtonB8.setText("Knight_Black");
        ButtonB8.setToolTipText("");
        ButtonB8.setActionCommand("jToggleButtonB8");
        ButtonB8.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonB8.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonB8.setName("ButtonB8"); // NOI18N
        ButtonB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonB8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB8);
        ButtonB8.setBounds(60, 0, 60, 60);

        ButtonC8.setBackground(new java.awt.Color(255, 255, 255));
        ButtonC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Black_Bishop.png"))); // NOI18N
        ButtonC8.setText("Black_Bishop");
        ButtonC8.setToolTipText("");
        ButtonC8.setActionCommand("jToggleButtonC8");
        ButtonC8.setMaximumSize(new java.awt.Dimension(60, 60));
        ButtonC8.setMinimumSize(new java.awt.Dimension(60, 60));
        ButtonC8.setName("ButtonC8"); // NOI18N
        ButtonC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonC8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC8);
        ButtonC8.setBounds(120, 0, 60, 60);

        NewBlack_Bishop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Bishop_Black.png"))); // NOI18N
        NewBlack_Bishop.setText("Bishop_Black");
        NewBlack_Bishop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBlack_BishopActionPerformed(evt);
            }
        });
        getContentPane().add(NewBlack_Bishop);
        NewBlack_Bishop.setBounds(550, 70, 60, 60);
        NewBlack_Bishop.hide();

        NewBlack_Knight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_Black.png"))); // NOI18N
        NewBlack_Knight.setText("Knight_Black");
        NewBlack_Knight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBlack_KnightActionPerformed(evt);
            }
        });
        getContentPane().add(NewBlack_Knight);
        NewBlack_Knight.setBounds(550, 130, 60, 60);
        NewBlack_Knight.hide();

        NewBlack_Rook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_Black.png"))); // NOI18N
        NewBlack_Rook.setText("Rook_Black");
        NewBlack_Rook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBlack_RookActionPerformed(evt);
            }
        });
        getContentPane().add(NewBlack_Rook);
        NewBlack_Rook.setBounds(550, 190, 60, 60);
        NewBlack_Rook.hide();

        NewBlack_Queen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Queen_Black.png"))); // NOI18N
        NewBlack_Queen.setText("Queen_Black");
        NewBlack_Queen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBlack_QueenActionPerformed(evt);
            }
        });
        getContentPane().add(NewBlack_Queen);
        NewBlack_Queen.setBounds(550, 250, 60, 60);
        NewBlack_Queen.hide();

        NewWhite_Rook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_White.png"))); // NOI18N
        NewWhite_Rook.setText("Rook_White");
        NewWhite_Rook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewWhite_RookActionPerformed(evt);
            }
        });
        getContentPane().add(NewWhite_Rook);
        NewWhite_Rook.setBounds(610, 190, 60, 60);
        NewWhite_Rook.hide();

        NewWhite_Bishop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Bishop_White.png"))); // NOI18N
        NewWhite_Bishop.setText("Bishop_White");
        NewWhite_Bishop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewWhite_BishopActionPerformed(evt);
            }
        });
        getContentPane().add(NewWhite_Bishop);
        NewWhite_Bishop.setBounds(610, 70, 60, 60);
        NewWhite_Bishop.hide();

        NewWhite_Knight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_White.png"))); // NOI18N
        NewWhite_Knight.setText("Knight_White");
        NewWhite_Knight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewWhite_KnightActionPerformed(evt);
            }
        });
        getContentPane().add(NewWhite_Knight);
        NewWhite_Knight.setBounds(610, 130, 60, 60);
        NewWhite_Knight.hide();

        NewWhite_Queen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Queen_white.png"))); // NOI18N
        NewWhite_Queen.setText("Queen_White");
        NewWhite_Queen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewWhite_QueenActionPerformed(evt);
            }
        });
        getContentPane().add(NewWhite_Queen);
        NewWhite_Queen.setBounds(610, 250, 60, 60);
        NewWhite_Queen.hide();

        jLabel1.setText("To Castle move King first");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 330, 170, 14);

        jLabel2.setText("Who's go?:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 30, 80, 14);

        WhoGO.setText("white");
        WhoGO.setName("WhoGo"); // NOI18N
        getContentPane().add(WhoGO);
        WhoGO.setBounds(610, 30, 60, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Warning:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(590, 350, 110, 20);

        Warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Warning.setName("Warning"); // NOI18N
        getContentPane().add(Warning);
        Warning.setBounds(500, 400, 220, 0);

        Warning1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Warning1.setText("Please make your move");
        getContentPane().add(Warning1);
        Warning1.setBounds(490, 380, 310, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonG1ActionPerformed
//        if (SelectORMove.equals("Select")) {
//            PieceSelected = ButtonG1.getText();
//            CheckingColour();
//            FindingPiece();
//            LastClickedColor = ButtonG1.getBackground();
//            ButtonG1.setBackground(Color.YELLOW);
//            LastClicked = ButtonG1;
//            SelectORMove = "Move";
//
//            //Player clicks to undo the selected piece
//            //Button doesn't turn yellow is place is empty
//        } else {
//            CheckingEmpty();
//            if (MoveSpaceFree = true) {
//                LastClicked.setIcon(null);
//                LastClicked.setText("");
//                LastClicked.setBackground(LastClickedColor);
//                ButtonG3.setText(PieceSelected);
//                try {
//                    SetNewSpace(ButtonG3);
//                } catch (IOException ex) {
//                    Logger.getLogger(ABoard.class.getName()).log(Level.SEVERE, null, ex);
//                    System.out.println("Sorry this has not worked");
//                }
//                SelectORMove = "Select";
//            } else {
//            System.out.println("Sorry this space is filled");
//            }
        Complete(ButtonG1);
    }//GEN-LAST:event_ButtonG1ActionPerformed

    private void ButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonH1ActionPerformed
        Complete(ButtonH1);
    }//GEN-LAST:event_ButtonH1ActionPerformed

    private void ButtonF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonF1ActionPerformed
        Complete(ButtonF1);
    }//GEN-LAST:event_ButtonF1ActionPerformed

    private void ButtonE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonE1ActionPerformed
        Complete(ButtonE1);
    }//GEN-LAST:event_ButtonE1ActionPerformed

    private void ButtonC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonC1ActionPerformed
        Complete(ButtonC1);       // TODO add your handling code here:
    }//GEN-LAST:event_ButtonC1ActionPerformed

    private void ButtonD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonD1ActionPerformed
        Complete(ButtonD1);
    }//GEN-LAST:event_ButtonD1ActionPerformed

    private void ButtonB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonB1ActionPerformed
        Complete(ButtonB1);
    }//GEN-LAST:event_ButtonB1ActionPerformed

    private void ButtonA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonA1ActionPerformed
        Complete(ButtonA1);
    }//GEN-LAST:event_ButtonA1ActionPerformed

    private void ButtonH7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonH7ActionPerformed
        Complete(ButtonH7);
    }//GEN-LAST:event_ButtonH7ActionPerformed

    private void ButtonG7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonG7ActionPerformed
        Complete(ButtonG7);
    }//GEN-LAST:event_ButtonG7ActionPerformed

    private void ButtonF7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonF7ActionPerformed
        Complete(ButtonF7);
    }//GEN-LAST:event_ButtonF7ActionPerformed

    private void ButtonE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonE7ActionPerformed
        Complete(ButtonE7);
    }//GEN-LAST:event_ButtonE7ActionPerformed

    private void ButtonD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonD7ActionPerformed
        Complete(ButtonD7);
    }//GEN-LAST:event_ButtonD7ActionPerformed

    private void ButtonC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonC7ActionPerformed
        Complete(ButtonC7);
    }//GEN-LAST:event_ButtonC7ActionPerformed

    private void ButtonB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonB7ActionPerformed
        Complete(ButtonB7);
    }//GEN-LAST:event_ButtonB7ActionPerformed

    private void ButtonA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonA7ActionPerformed
        Complete(ButtonA7);
    }//GEN-LAST:event_ButtonA7ActionPerformed

    private void ButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonH5ActionPerformed
        Complete(ButtonH5);
    }//GEN-LAST:event_ButtonH5ActionPerformed

    private void ButtonA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonA6ActionPerformed
        Complete(ButtonA6);
    }//GEN-LAST:event_ButtonA6ActionPerformed

    private void ButtonB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonB6ActionPerformed
        Complete(ButtonB6);
    }//GEN-LAST:event_ButtonB6ActionPerformed

    private void ButtonC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonC6ActionPerformed
        Complete(ButtonC6);
    }//GEN-LAST:event_ButtonC6ActionPerformed

    private void ButtonD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonD6ActionPerformed
        Complete(ButtonD6);
    }//GEN-LAST:event_ButtonD6ActionPerformed

    private void ButtonE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonE6ActionPerformed
        Complete(ButtonE6);
    }//GEN-LAST:event_ButtonE6ActionPerformed

    private void ButtonF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonF6ActionPerformed
        Complete(ButtonF6);
    }//GEN-LAST:event_ButtonF6ActionPerformed

    private void ButtonH6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonH6ActionPerformed
        Complete(ButtonH6);
    }//GEN-LAST:event_ButtonH6ActionPerformed

    private void ButtonG6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonG6ActionPerformed
        Complete(ButtonG6);
    }//GEN-LAST:event_ButtonG6ActionPerformed

    private void ButtonG5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonG5ActionPerformed
        Complete(ButtonG6);
    }//GEN-LAST:event_ButtonG5ActionPerformed

    private void ButtonF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonF5ActionPerformed
        Complete(ButtonF5);
    }//GEN-LAST:event_ButtonF5ActionPerformed

    private void ButtonE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonE5ActionPerformed
        Complete(ButtonE5);
    }//GEN-LAST:event_ButtonE5ActionPerformed

    private void ButtonD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonD5ActionPerformed
        Complete(ButtonD5);
    }//GEN-LAST:event_ButtonD5ActionPerformed

    private void ButtonC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonC5ActionPerformed
        Complete(ButtonC5);
    }//GEN-LAST:event_ButtonC5ActionPerformed

    private void ButtonB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonB5ActionPerformed
        Complete(ButtonB5);
    }//GEN-LAST:event_ButtonB5ActionPerformed

    private void ButtonA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonA5ActionPerformed
        Complete(ButtonA5);
    }//GEN-LAST:event_ButtonA5ActionPerformed

    private void ButtonE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonE3ActionPerformed
        Complete(ButtonE3);
    }//GEN-LAST:event_ButtonE3ActionPerformed

    private void ButtonB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonB4ActionPerformed
        Complete(ButtonB4);
    }//GEN-LAST:event_ButtonB4ActionPerformed

    private void ButtonD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonD3ActionPerformed
        Complete(ButtonD3);
    }//GEN-LAST:event_ButtonD3ActionPerformed

    private void ButtonD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonD4ActionPerformed
        Complete(ButtonD4);
    }//GEN-LAST:event_ButtonD4ActionPerformed

    private void ButtonG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonG3ActionPerformed
        Complete(ButtonG3);
    }//GEN-LAST:event_ButtonG3ActionPerformed

    private void ButtonB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonB3ActionPerformed
        Complete(ButtonB3);
    }//GEN-LAST:event_ButtonB3ActionPerformed

    private void ButtonA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonA4ActionPerformed
        Complete(ButtonA4);
    }//GEN-LAST:event_ButtonA4ActionPerformed

    private void ButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonH4ActionPerformed
        Complete(ButtonH4);
    }//GEN-LAST:event_ButtonH4ActionPerformed

    private void ButtonC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonC3ActionPerformed
        Complete(ButtonC3);
    }//GEN-LAST:event_ButtonC3ActionPerformed

    private void ButtonA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonA3ActionPerformed
        Complete(ButtonA3);
    }//GEN-LAST:event_ButtonA3ActionPerformed

    private void ButtonE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonE4ActionPerformed
        Complete(ButtonE4);
    }//GEN-LAST:event_ButtonE4ActionPerformed

    private void ButtonF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonF4ActionPerformed
        Complete(ButtonF4);
    }//GEN-LAST:event_ButtonF4ActionPerformed

    private void ButtonF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonF3ActionPerformed
        Complete(ButtonF3);
    }//GEN-LAST:event_ButtonF3ActionPerformed

    private void ButtonC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonC4ActionPerformed
        Complete(ButtonC4);
    }//GEN-LAST:event_ButtonC4ActionPerformed

    private void ButtonG4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonG4ActionPerformed
        Complete(ButtonG4);
    }//GEN-LAST:event_ButtonG4ActionPerformed

    private void ButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonH3ActionPerformed
        Complete(ButtonH3);
    }//GEN-LAST:event_ButtonH3ActionPerformed

    private void ButtonB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonB2ActionPerformed
        Complete(ButtonB2);
    }//GEN-LAST:event_ButtonB2ActionPerformed

    private void ButtonA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonA8ActionPerformed
        Complete(ButtonA8);
    }//GEN-LAST:event_ButtonA8ActionPerformed

    private void ButtonH8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonH8ActionPerformed
        Complete(ButtonH8);
    }//GEN-LAST:event_ButtonH8ActionPerformed

    private void ButtonE8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonE8ActionPerformed
        Complete(ButtonE8);
    }//GEN-LAST:event_ButtonE8ActionPerformed

    private void ButtonF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonF2ActionPerformed
        Complete(ButtonF2);
    }//GEN-LAST:event_ButtonF2ActionPerformed

    private void ButtonG8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonG8ActionPerformed
        Complete(ButtonG8);
    }//GEN-LAST:event_ButtonG8ActionPerformed

    private void ButtonA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonA2ActionPerformed
        Complete(ButtonA2);
    }//GEN-LAST:event_ButtonA2ActionPerformed

    private void ButtonC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonC2ActionPerformed
        Complete(ButtonC2);
    }//GEN-LAST:event_ButtonC2ActionPerformed

    private void ButtonF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonF8ActionPerformed
        Complete(ButtonF8);
    }//GEN-LAST:event_ButtonF8ActionPerformed

    private void ButtonG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonG2ActionPerformed
        Complete(ButtonG2);
    }//GEN-LAST:event_ButtonG2ActionPerformed

    private void ButtonE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonE2ActionPerformed
        Complete(ButtonE2);
    }//GEN-LAST:event_ButtonE2ActionPerformed

    private void ButtonD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonD8ActionPerformed
        Complete(ButtonD8);
    }//GEN-LAST:event_ButtonD8ActionPerformed

    private void ButtonD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonD2ActionPerformed
        Complete(ButtonD2);
    }//GEN-LAST:event_ButtonD2ActionPerformed

    private void ButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonH2ActionPerformed
        Complete(ButtonH2);
    }//GEN-LAST:event_ButtonH2ActionPerformed

    private void ButtonB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonB8ActionPerformed
        Complete(ButtonB8);
    }//GEN-LAST:event_ButtonB8ActionPerformed

    private void ButtonC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonC8ActionPerformed
        Complete(ButtonC8);
    }//GEN-LAST:event_ButtonC8ActionPerformed

    private void NewBlack_QueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBlack_QueenActionPerformed
        NewPiece = NewBlack_Queen;
        ChangePiece(NewBlack_Queen);
    }//GEN-LAST:event_NewBlack_QueenActionPerformed

    private void NewBlack_RookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBlack_RookActionPerformed
        NewPiece = NewBlack_Rook;
        ChangePiece(NewBlack_Rook);
    }//GEN-LAST:event_NewBlack_RookActionPerformed

    private void NewBlack_KnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBlack_KnightActionPerformed
        NewPiece = NewBlack_Knight;
        ChangePiece(NewBlack_Knight);
    }//GEN-LAST:event_NewBlack_KnightActionPerformed

    private void NewBlack_BishopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBlack_BishopActionPerformed
        NewPiece = NewBlack_Bishop;
        ChangePiece(NewBlack_Bishop);
    }//GEN-LAST:event_NewBlack_BishopActionPerformed

    private void NewWhite_BishopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewWhite_BishopActionPerformed
        NewPiece = NewWhite_Bishop;
        ChangePiece(NewWhite_Bishop);
    }//GEN-LAST:event_NewWhite_BishopActionPerformed

    private void NewWhite_KnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewWhite_KnightActionPerformed
        NewPiece = NewWhite_Knight;
        ChangePiece(NewWhite_Knight);
    }//GEN-LAST:event_NewWhite_KnightActionPerformed

    private void NewWhite_RookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewWhite_RookActionPerformed
        NewPiece = NewWhite_Rook;
        ChangePiece(NewWhite_Rook);
    }//GEN-LAST:event_NewWhite_RookActionPerformed

    private void NewWhite_QueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewWhite_QueenActionPerformed
        NewPiece = NewWhite_Queen;
        ChangePiece(NewWhite_Queen);
    }//GEN-LAST:event_NewWhite_QueenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonA1;
    private javax.swing.JButton ButtonA2;
    private javax.swing.JButton ButtonA3;
    private javax.swing.JButton ButtonA4;
    private javax.swing.JButton ButtonA5;
    private javax.swing.JButton ButtonA6;
    private javax.swing.JButton ButtonA7;
    private javax.swing.JButton ButtonA8;
    private javax.swing.JButton ButtonB1;
    private javax.swing.JButton ButtonB2;
    private javax.swing.JButton ButtonB3;
    private javax.swing.JButton ButtonB4;
    private javax.swing.JButton ButtonB5;
    private javax.swing.JButton ButtonB6;
    private javax.swing.JButton ButtonB7;
    private javax.swing.JButton ButtonB8;
    private javax.swing.JButton ButtonC1;
    private javax.swing.JButton ButtonC2;
    private javax.swing.JButton ButtonC3;
    private javax.swing.JButton ButtonC4;
    private javax.swing.JButton ButtonC5;
    private javax.swing.JButton ButtonC6;
    private javax.swing.JButton ButtonC7;
    private javax.swing.JButton ButtonC8;
    private javax.swing.JButton ButtonD1;
    private javax.swing.JButton ButtonD2;
    private javax.swing.JButton ButtonD3;
    private javax.swing.JButton ButtonD4;
    private javax.swing.JButton ButtonD5;
    private javax.swing.JButton ButtonD6;
    private javax.swing.JButton ButtonD7;
    private javax.swing.JButton ButtonD8;
    private javax.swing.JButton ButtonE1;
    private javax.swing.JButton ButtonE2;
    private javax.swing.JButton ButtonE3;
    private javax.swing.JButton ButtonE4;
    private javax.swing.JButton ButtonE5;
    private javax.swing.JButton ButtonE6;
    private javax.swing.JButton ButtonE7;
    private javax.swing.JButton ButtonE8;
    private javax.swing.JButton ButtonF1;
    private javax.swing.JButton ButtonF2;
    private javax.swing.JButton ButtonF3;
    private javax.swing.JButton ButtonF4;
    private javax.swing.JButton ButtonF5;
    private javax.swing.JButton ButtonF6;
    private javax.swing.JButton ButtonF7;
    private javax.swing.JButton ButtonF8;
    private javax.swing.JButton ButtonG1;
    private javax.swing.JButton ButtonG2;
    private javax.swing.JButton ButtonG3;
    private javax.swing.JButton ButtonG4;
    private javax.swing.JButton ButtonG5;
    private javax.swing.JButton ButtonG6;
    private javax.swing.JButton ButtonG7;
    private javax.swing.JButton ButtonG8;
    private javax.swing.JButton ButtonH1;
    private javax.swing.JButton ButtonH2;
    private javax.swing.JButton ButtonH3;
    private javax.swing.JButton ButtonH4;
    private javax.swing.JButton ButtonH5;
    private javax.swing.JButton ButtonH6;
    private javax.swing.JButton ButtonH7;
    private javax.swing.JButton ButtonH8;
    private javax.swing.JButton NewBlack_Bishop;
    private javax.swing.JButton NewBlack_Knight;
    private javax.swing.JButton NewBlack_Queen;
    private javax.swing.JButton NewBlack_Rook;
    private javax.swing.JButton NewWhite_Bishop;
    private javax.swing.JButton NewWhite_Knight;
    private javax.swing.JButton NewWhite_Queen;
    private javax.swing.JButton NewWhite_Rook;
    private javax.swing.JLabel Warning;
    private javax.swing.JLabel Warning1;
    private javax.swing.JLabel WhoGO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
    public void CheckingColour() {
        if (Go.equalsIgnoreCase("White") && PieceSelected.toLowerCase().contains("white")) {
            Warning1.setText("Please move");
        } else if (Go.equalsIgnoreCase("Black") && PieceSelected.toLowerCase().contains("white")) {
            Warning1.setText("Sorry it is not whites go. Black please move");
        } else if (Go.equalsIgnoreCase("White") && PieceSelected.toLowerCase().contains("black")) {
            Warning1.setText("Sorry it is not blacks go. White please move");
        } else if (PieceSelected.isEmpty()) {
            Warning1.setText("Sorry there is no pieces here... Please pick another go.");
        }
    }

    public static void FindingPiece() {
        int len = PieceSelected.length();
        if (PieceSelected.length() > 5) {
            PieceChosen = PieceSelected.substring(0, len - 6);
        }

    }

    public static void CheckingEmpty(JButton pressed) {
        ColourMatching = pressed.getText();
        if (ColourMatching.length() > 5) {
            int len = ColourMatching.length();
            ColourMatching = ColourMatching.substring(len - 5, len);
//            System.out.println(ColourMatching);
        }

//        if (.isEmpty()) {
////            System.out.println("This is empty");
//            MoveSpaceFree = true;
//
//        } else {
////            System.out.println("Sorry. This place is currently filled! Please move somewhere else");
//            MoveSpaceFree = false;
//        }
    }

    public static void ChessPromotion(JButton NewPlace) {

    }

    public void SetNewSpace(JButton pressed) throws IOException {
        if (PieceSelected.toLowerCase().contains("white")) {
            if (PieceChosen.equalsIgnoreCase("Pawn")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_White.png")));
            } else if (PieceChosen.equalsIgnoreCase("King")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/King_White.png")));
            } else if (PieceChosen.equalsIgnoreCase("Queen")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Queen_White.png")));
            } else if (PieceChosen.equalsIgnoreCase("Rook")) {;
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_White.png")));
            } else if (PieceChosen.equalsIgnoreCase("Knight")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_White.png")));
            } else if (PieceChosen.equalsIgnoreCase("Bishop")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Bishop_White.png")));
            }
        } else {
            if (PieceChosen.equalsIgnoreCase("Pawn")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Pawn_Black.png")));
            } else if (PieceChosen.equalsIgnoreCase("King")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/King_Black.png")));
            } else if (PieceChosen.equalsIgnoreCase("Queen")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Queen_Black.png")));
            } else if (PieceChosen.equalsIgnoreCase("Rook")) {;
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_Black.png")));
            } else if (PieceChosen.equalsIgnoreCase("Knight")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_Black.png")));
            } else if (PieceChosen.equalsIgnoreCase("Bishop")) {
                pressed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Bishop_Black.png")));
            }
        }
    }

    public void Complete(JButton Pressed) {
        if (SelectORMove.equals("Select")) {
            PieceSelected = Pressed.getText();
            if (PieceSelected.length() > 5) {
                CheckingColour();
                System.out.println(PieceSelected);
                System.out.println(Go);
                if (PieceSelected.toLowerCase().contains(Go)) {
                    FindingPiece();
                    LastClickedColor = Pressed.getBackground();
                    Pressed.setBackground(Color.YELLOW);
                    LastClicked = Pressed;
                    SelectORMove = "Move";

                    //Player clicks to undo the selected piece
                    //Button doesn't turn yellow is place is empty  
                }
            } else {
                Warning1.setText("Sorry you have selected a space with no pieces. ");
            }

        } else {
            CheckingEmpty(Pressed);
            CheckingColour();
            if ((Pressed.getBackground() == Color.YELLOW)) {
                Pressed.setBackground(LastClickedColor);
                SelectORMove = "Select";
            } else {
                if ((ColourMatching.equalsIgnoreCase(Go)) == false) {
                    if ((Pressed.getName().toLowerCase().contains("1") && (PieceSelected.toLowerCase().contains("black")) && (PieceSelected.toLowerCase().contains("pawn"))) || (Pressed.getName().toLowerCase().contains("8") && (PieceSelected.toLowerCase().contains("white")) && (PieceSelected.toLowerCase().contains("pawn")))) {
                        if (PieceSelected.toLowerCase().contains("white")) {
                            NewWhite_Bishop.show();
                            NewWhite_Queen.show();
                            NewWhite_Rook.show();
                            NewWhite_Knight.show();
                        } else {
                            NewBlack_Bishop.show();
                            NewBlack_Queen.show();
                            NewBlack_Rook.show();
                            NewBlack_Knight.show();
                        }
                        NewClicked = Pressed;
                        Pressed.setBackground(Color.YELLOW);
                        LastClicked.setBackground(LastClickedColor);
                    } else if (LastClicked.getName().toLowerCase().contains("e1") && PieceSelected.toLowerCase().contains("king") && PieceSelected.toLowerCase().contains("white") && (Pressed.getName().toLowerCase().contains("1")) && (Pressed.getName().toLowerCase().contains("g"))) {
                        ButtonG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/King_White.png")));
                        ButtonG1.setText("King_White");
                        ButtonF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_White.png")));
                        ButtonF1.setText("Rook_White");
                        ButtonE1.setIcon(null);
                        ButtonE1.setText("");
                        ButtonH1.setIcon(null);
                        ButtonH1.setText("");
                        LastClicked.setBackground(LastClickedColor);
                    } else if (LastClicked.getName().toLowerCase().contains("e1") && PieceSelected.toLowerCase().contains("king") && PieceSelected.toLowerCase().contains("white") && (Pressed.getName().toLowerCase().contains("1")) && (Pressed.getName().toLowerCase().contains("c"))) {
                        ButtonC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/King_White.png")));
                        ButtonC1.setText("King_White");
                        ButtonB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_White.png")));
                        ButtonB1.setText("Rook_White");
                        ButtonE1.setIcon(null);
                        ButtonE1.setText("");
                        ButtonA1.setIcon(null);
                        ButtonA1.setText("");
                        LastClicked.setBackground(LastClickedColor);
                    } else if (LastClicked.getName().toLowerCase().contains("e8") && PieceSelected.toLowerCase().contains("king") && PieceSelected.toLowerCase().contains("black") && (Pressed.getName().toLowerCase().contains("8")) && (Pressed.getName().toLowerCase().contains("g"))) {
                        ButtonG8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/King_Black.png")));
                        ButtonG8.setText("King_Black");
                        ButtonF8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_Black.png")));
                        ButtonF8.setText("Rook_Black");
                        ButtonE8.setIcon(null);
                        ButtonE8.setText("");
                        ButtonH8.setIcon(null);
                        ButtonH8.setText("");
                        LastClicked.setBackground(LastClickedColor);
                    } else if (LastClicked.getName().toLowerCase().contains("e8") && PieceSelected.toLowerCase().contains("king") && PieceSelected.toLowerCase().contains("black") && (Pressed.getName().toLowerCase().contains("8")) && (Pressed.getName().toLowerCase().contains("c"))) {
                        ButtonC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/King_Black.png")));
                        ButtonC1.setText("King_Black");
                        ButtonB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_Black.png")));
                        ButtonB1.setText("Rook_Black");
                        ButtonE1.setIcon(null);
                        ButtonE1.setText("");
                        ButtonA1.setIcon(null);
                        ButtonA1.setText("");
                        LastClicked.setBackground(LastClickedColor);
                    } else {
//                if ((ColourMatching.equalsIgnoreCase(Go)) == false) {
                        LastClicked.setIcon(null);
                        LastClicked.setText("");
                        LastClicked.setBackground(LastClickedColor);
                        Pressed.setText(PieceSelected);
                        try {
                            SetNewSpace(Pressed);
                        } catch (IOException ex) {
                            Logger.getLogger(ABoard.class.getName()).log(Level.SEVERE, null, ex);
                            System.out.println("Sorry this has not worked");
                        }
                        SelectORMove = "Select";
                        if (Go.equalsIgnoreCase("white")) {
                            Go = "black";
                            WhoGO.setText("black");
                        } else {
                            Go = "white";
                            WhoGO.setText("white");
                        }

                    }
                } else {
                    Warning1.setText("Sorry this space already has one of your colour is");
                }
            }
        }
    }

    public void ChangePiece(JButton NewPiece) {
        String NewButtonText = NewPiece.getText();
//        NewPiece.setBackground(Color.YELLOW);
        if (NewButtonText.toLowerCase().contains("white")) {
            if (NewButtonText.toLowerCase().contains("rook")) {
                NewClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_White.png")));
                NewClicked.setText("Rook_White");
            } else if (NewButtonText.toLowerCase().contains("queen")) {
                NewClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Queen_White.png")));
                NewClicked.setText("Queen_White");
            } else if (NewButtonText.toLowerCase().contains("knight")) {
                NewClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_White.png")));
                NewClicked.setText("Knight_White");
            } else if (NewButtonText.toLowerCase().contains("bishop")) {
                NewClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Bishop_White.png")));
                NewClicked.setText("Bishop_White");
            }
            NewWhite_Bishop.hide();
            NewWhite_Queen.hide();
            NewWhite_Rook.hide();
            NewWhite_Knight.hide();
        } else {
            if (NewButtonText.toLowerCase().contains("rook")) {
                NewClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Rook_Black.png")));
                NewClicked.setText("Rook_Black");
            } else if (NewButtonText.toLowerCase().contains("queen")) {
                NewClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Queen_Black.png")));
                NewClicked.setText("Queen_Black");
            } else if (NewButtonText.toLowerCase().contains("knight")) {
                NewClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Knight_Black.png")));
                NewClicked.setText("Knight_Black");
            } else if (NewButtonText.toLowerCase().contains("bishop")) {
                NewClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/christmaschessgame/Bishop_Black.png")));
                NewClicked.setText("Bishop_Black");
            }
            NewBlack_Bishop.hide();
            NewBlack_Queen.hide();
            NewBlack_Rook.hide();
            NewBlack_Knight.hide();
        }
        LastClicked.setBackground(LastClickedColor);
        LastClicked.setIcon(null);
        LastClicked.setText("");
    }
}


//Reaching the end of the board convert to queen etc
